version: '3'

services:

  nodered:
    image: nodered/node-red-docker:rpi
    ports:
      - 1880:1880
    volumes:
      - nodered:/data
    command: bash -c "sudo apt-get update && sudo apt-get install python-rpi.gpio python3-rpi.gpio"

  noip:
    image: "hypriot/rpi-noip"
    volumes:
      - ./config/no-ip2.conf:/usr/local/etc/no-ip2.conf

volumes:
  nodered:
