FROM nodered/node-red-docker:0.17.3-rpi

RUN npm install node-red-node-serialport xbee-api node-red-contribe-xbee-api node-red-contrib-chatbot node-red-node-twitter node-red-contrib-ibm-watson-iot node-red-contrib-play-audio
 
